window["bddcontent"] = `
<?php
// Echo Statement Inside HTML
echo "<p>This content is generated by PHP.</p>";
?>
<html>
    <body>
        <h1>Using PHP echo inside HTML</h1>
    </body>
</html>
`;